// Generated by https://quicktype.io

export interface Test {
    filters:     Filters;
    resultSet:   ResultSet;
    competition: Competition;
    matches:     Match[];
}

export interface Competition {
    id:     number;
    name:   string;
    code:   string;
    type:   string;
    emblem: string;
}

export interface Filters {
    season:   string;
    matchday: string;
}

export interface Match {
    area:          Area;
    competition:   Competition;
    season:        Season;
    id:            number;
    utcDate:       string;
    status:        string;
    minute:        string;
    injuryTime:    number;
    attendance:    number | null;
    venue:         string;
    matchday:      number;
    stage:         string;
    group:         null;
    lastUpdated:   string;
    homeTeam:      Team;
    awayTeam:      Team;
    score:         Score;
    goals:         Goal[];
    penalties:     Penalty[];
    bookings:      any[];
    substitutions: any[];
    odds:          Odds;
    referees:      Coach[];
}

export interface Area {
    id:   number;
    name: Name;
    code: string;
    flag: string;
}

export enum Name {
    Germany = "Germany",
    Switzerland = "Switzerland",
}

export interface Team {
    id:         number;
    name:       string;
    shortName:  string;
    tla:        string;
    crest:      string;
    coach:      Coach;
    leagueRank: number;
    formation:  string;
    lineup:     any[];
    bench:      any[];
}

export interface Coach {
    id:          number;
    name:        string;
    nationality: Name;
    type?:       string;
}

export interface Goal {
    minute:     number;
    injuryTime: number | null;
    type:       string;
    team:       Scorer;
    scorer:     Scorer;
    assist:     Scorer | null;
    score:      FullTime;
}

export interface Scorer {
    id:   number;
    name: string;
}

export interface FullTime {
    home: number;
    away: number;
}

export interface Odds {
    homeWin: number;
    draw:    number;
    awayWin: number;
}

export interface Penalty {
    player: Scorer;
    team:   Scorer;
    scored: boolean;
}

export interface Score {
    winner:   string;
    duration: string;
    fullTime: FullTime;
    halfTime: FullTime;
}

export interface Season {
    id:              number;
    startDate:       string;
    endDate:         string;
    currentMatchday: number;
    winner:          null;
    stages:          string[];
}

export interface ResultSet {
    count:  number;
    first:  string;
    last:   string;
    played: number;
}
